### PR TITLE
Fix the submodules upload issue #198

### PR DESCRIPTION
**Pull request by mabhub**

### CODE REVIEW

**Comment by wesleylancel** [comment]
:thumbsup:

**Comment by jverdeyen** [comment]
:+1:

**Comment by mkllnk** [comment]
Some explanation would be nice. :-)

For the people who wonder what this change does:
```
a="$(seq 10)"  # a is an array containing elements 1 .. 10
foo $a[@]      # foo is called with ten arguments: 1 2 3 4 5 6 7 8 9 10
foo "$a[@]"    # foo is called with one argument: 1 2 3 4 5 6 7 8 9 10[@]
```

Looking at this a bit closer, I think that the `has` function is over-complicated. What about this change:
```bash
	# current version
	echo " $@ " | grep -q " $(escape "$item") "

	# better version?
	echo "$@" | grep -q -F "$item"
```

**Comment by jverdeyen** [comment]
Thanks!

**Comment by mkllnk** [comment]
Thanks to @mabhub!

**Pull request merged**
