### PR TITLE
Delete files in .git-ftp-include only if locally deleted

### PR DESCRIPTION
**Pull request by mkllnk**
Adresses issue #169.

I'm not sure if the test for a slash as last character works in all shells:

```
 if [ "${TARGET: -1}" != '/' ]; then
   ...
 fi
```

### CODE REVIEW

**Comment by resmo** [comment]
@mkllnk is this ready to merge?

**Comment by mkllnk** [comment]
I was not able to test it under Windows or OSX.

The last feedback from @colinsanford was: "Somethings still not quite right unfortunately." But no further explanation. I don't know what could go wrong with the current code, but you never know. Do you have OSX running?

I would risk merging it.

**Comment by resmo** [comment]
Yes, I have access to a OSX box. Travis has OSX support as well, but this would take some efforts.

**Comment by mkllnk** [comment]
Hey, I had the opportunity to test on a Windows installation. The current branch has the missing-mktemp problem, but after merging the develop branch, basic commands worked under Git for Windows. I think it's ready.

**Pull request merged**
