### PR TITLE
Use ronn instead of pandoc for generating man page

### PR DESCRIPTION
**Pull request by sudaraka**

### CODE REVIEW

**Comment by mkllnk** [comment]
Hello @sudaraka, thanks for the pull request.

I'm not familiar with ronn or pandoc. Can you explain why we should use ronn?

**Comment by mkllnk** [comment]
Seems like `pandoc` is installed on most Debian based distributions while `ronn` isn't.
`pandoc` supports a lot more formats and is also used to generate HTML in the git-ftp project.
It has a much higher footprint though.
```
pandoc: 26.6 M
ronn: 71.7 k
```
We should keep our dependency list as short as possible.

I would keep `pandoc` for now. Other opinions?

**Comment by resmo** [comment]
I also want to keep pandoc. But we could also support ronn as well, so IMHO it is more a question of ronn and pandoc. Make another make target for ronn? Thoughts?

**Comment by sudaraka** [comment]
The issue I have with pandoc (which very well be an edge case) is that I have to download over 1GB of haskel and dependency packages just to convert a .md to a manpage. (Please see issue #179). I'm fine with having it as a build option.

**Comment by mkllnk** [comment]
Fair enough. I merged your change into our branch and added a new make target.

I had just one more idea: `make man` could test if pandoc is available and try ronn otherwise. If anyone has fun implementing that... :-)

**Pull request closed without merging**
