### PR TITLE
Mac OS X install note with XCode and Command Line Tools requirement

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
if i remember correctly, it just show that it require command line tools (popup) when i run the command to install

**Comment by mkllnk** [comment]
According to http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/ you can install the command line tools via `xcode-select --install` in the console. That sounds a bit easier. Can anyone confirm this?

**Comment by adrum** [comment]
@mkllnk Yup. That is the easiest way to get the latest command line tools and that's all that should be needed. They will be updated from the App Store from then on.

**Comment by samsonasik** [comment]
ok, i've updated to include `xcode-select --install`

**Pull request merged**
