### PR TITLE
Installation in windows (updated)

### PR DESCRIPTION
**Pull request by vgrados2**

### CODE REVIEW

**Comment by mkllnk** [comment]
Thank you for your contribution. I think your new way should actually replace msysgit since Git for Windows superseded msysgit. I will try do merge the two versions together.

**Comment by mkllnk** [comment]
What do you think about this version?

I know, I didn't use `git clone` as in your example, but it should still work. Would you like to verify that this way works?

**Comment by vgrados2** [comment]
Yes, I'll check it

**Comment by vgrados2** [comment]
Do the test and everything is correct

**Comment by jonbgallant** [comment]
Here are steps to install on windows via chocolately http://blog.jongallant.com/2017/01/install-git-ftp-windows/

**Pull request merged**
